config/routes.rb
Rails.application.routes.draw do
  resources :approves

  resources :news_letters do
    collection do
      post :adding_email
      get :send_mail
      end
      member do 
        get :unsubscribe
      end
  end

 resources :teams

 devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks" }

  
  resources :blogs do
    collection do
      get :search
      get :search_sphinx
      get :latest_blogs
      get :display_category
      get :display_tags
    end
  end

resources :users do
  collection do
    post :permissions
  end
end

 root 'blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
mount_uploader :avatar, AvatarUploader
	extend FriendlyId
  friendly_id :name, use: :slugged
# This method associates the attribute ":avatar" with a file attachment
  # has_attached_file :avatar, styles: {
  #   thumb: '100x100>',
  #   square: '200x200#',
  #   medium: '300x300>'
  # }

  # # Validate the attached image is image/jpg, image/png, etc
  # validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  belongs_to :team, :foreign_key => 'team_id'
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
 # before_action :authenticate_user!
  # skip_before_filter :authenticate_user!, :only => [:index, :show, :latest_blogs, :display_category, :display_tags]
  respond_to :html

  def index
    flash[:clear]
    @blogs = Blog.order('created_at DESC',).paginate(:page=>params[:page],:per_page=>5)
    display_all_tags
    respond_with(@blogs)
  end

  def show
    flash[:clear]
    @blogs = Blog.all
    display_all_tags
    respond_with(@blog)
  end

  def new
    
    @blog = Blog.new
    respond_with(@blog)
 
  end

  def edit

  end

  def create
    @blog = Blog.new(blog_params)
    @newsletter = NewsLetter.all
       if @blog.save
    @newsletter.each do |i|
      if i.subscribed?
        @nid = i.id
        @uri = request.original_url
        @email = i.email
        BlogsMailer.blog_update(@blog,@email,@uri,@nid).deliver
      end
    end
  end
    respond_with(@blog)
  end

  def update
    @blog.update(blog_params)
    respond_with(@blog)
  end

  def destroy
    @blog.destroy
    respond_with(@blog)
  end


 def search_sphinx
     tokens = []
    blogs1 =Blog.where("category LIKE ?", "%#{params[:q]}%")
       
    blogs1.each do |blog|
      tokens << "{ \"id\":\"#{blog.category}\",\"category\":\"#{blog.category}\"}"
    end
    puts tokens
    render :text => "[#{tokens.join(",")}]"
  end

  def search
    @blogs1 = Blog.where("blogs.category LIKE ?", "%#{params[:category]}%")
    render :action => 'index'
  end

  def latest_blogs
    @blogs = Blog.last(2).reverse
    render :layout => false
  end

  def display_category
    @categories = Blog.where("blogs.category LIKE ?", "%#{params[:category]}%").order('created_at DESC',).paginate(:page=>params[:page],:per_page=>5)
    display_all_tags
  end


  def display_tags
    @tags = Blog.where("blogs.tags LIKE ?", "%#{params[:tags]}%").order('created_at DESC',).paginate(:page=>params[:page],:per_page=>5)
    display_all_tags
  end

  def display_all_tags
    @display_all = Blog.all
    @tag = []
    @category = []
    @display_all.each do |blog|
      @tags_all = blog.tags.split(',')
      @Categories_all = blog.category.split(',')
      @tags_all.each do |ta|
        @tag << ta
      end
      @Categories_all.each do |cat|
        @category << cat
      end
    end
  end

def original_url
  base_url + original_fullpath
end

  private
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:name, :details, :category, :tags, :post_date, :blog_video, :avatar, :user_id,:slug , :author, :link, :team_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
	def blog_count(category)
		count = Blog.where("blogs.category LIKE ?", "%#{category}%").count
		return count
	end

end

app/views/blogs/_category_and_tags.html.erb
<div class="box">
  <h3>Categories</h3>
  <ul class="list-unstyled">
    <% @category.uniq.each do |c| %>
    <li><a href="<%= display_category_blogs_path(:category => c) %>"><i class="fa fa-angle-double-right"></i><%= c %><span class="badge"><%= blog_count(c) %></span></a></li>
    <% end %>
  </ul>
</div>
<div class="box box-tags">
  <h3>Tags</h3>
  <% @tag.uniq.each do |t| %>
  <a href="<%= display_tags_blogs_path(:tags => t) %>"><span class="text-14"><%= t %>&nbsp</span></a>
  <% end %> 
</div>

app/views/blogs/display_category.html.erb
<%#= javascript_include_tag "jquery-1.6.2.min", "jquery.tokeninput" %>
<%#= stylesheet_link_tag    "token-input", "token-input-facebook" %>
<!--   <#script type="text/javascript">
    $(document).ready(function() {
      $("#name").tokenInput('blogs/search_sphinx?q=', {
        theme: "facebook",
        hintText: "Search blog by Name",
        noResultsText: "No results found",
        searchingText: "Searching...",
        tokenLimit: 1
      });
    })
    </#script> -->

    <script type="text/javascript">
      jQuery(document).ready(function($){
        $(".blog-post-body p").each(function(){
          if ($(this).text().length > 500) {
            $(this).text($(this).text().substr(0, 495));
            $(this).append('...');
          }
        });
      });
    </script>


    <div id="page-wrapper" class="">
      
      <section class="breadcrumb-wrapper" >
        <div class="container">
          <h2>New Blogs</h2>
          <ol class="breadcrumb">
            <li><a href="<%= root_path %>">Home</a></li>
            <li class="active">Rank Blogs</li>
          </ol>
        </div>
      </section>
      <section class="content bg-color-2 right-sidebar" id="blog">
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-lg-9 blog-content">
              <% @categories.each do |blog| %>
              <div class="blog-post">
               <%= image_tag blog.avatar,:class => "img-responsive" ,:alt => ""%>
               <div class="blog-post-detail">
                <span><i class="fa fa-calendar"></i><%= blog.post_date.strftime("%d-%m-%Y") %></span>
                <span><i class="fa fa-comment"></i>11</span>
                <span><i class="fa fa-thumbs-up"></i>23</span>
                <span class="text-light hidden-xs"><a href="#"><%= blog.category %></a>, <a href="#"><%= blog.tags %></a></span>
              </div>
              <div class="blog-post-body">
                <a href=""><h3><%= link_to blog.name, blog %></h3></a>
                <p><%= truncate(blog.details,:length => 500 ,escape: false).html_safe %></p>
                <div>
                  <a href="<%= blog_path(blog) %>" class="btn btn-primary"><i class="fa fa-chevron-right"></i>Read More</a>
                </div>
              </div>
            </div>
            <% end %> 
            <ul class="pagination">
              <li ><%= will_paginate @categories, :container => false %></li>
            </ul><br>
          </div>
          <br>
          <div class="col-md-4 col-lg-3 blog-sidebar">
            <div class="box">
              <h3>Search</h3>
              <form>
                <fieldset>
                  <div class="form-group nospace">
                    <div class="input-group">
                      <input type="text" class="form-control" id="search" placeholder="Search" required>
                      <span class="input-group-btn"><button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button></span>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div> 
            <%= render partial: "category_and_tags" %>
          </div>
        </div>
      </div>
    </section>
  </div>

app/views/blogs/display_tags.html.erb
<%#= javascript_include_tag "jquery-1.6.2.min", "jquery.tokeninput" %>
  <%#= stylesheet_link_tag    "token-input", "token-input-facebook" %>
<!--   <#script type="text/javascript">
    $(document).ready(function() {
      $("#name").tokenInput('blogs/search_sphinx?q=', {
        theme: "facebook",
        hintText: "Search blog by Name",
        noResultsText: "No results found",
        searchingText: "Searching...",
        tokenLimit: 1
      });
    })
  </#script> -->
    <script type="text/javascript">
  jQuery(document).ready(function($){
  $(".blog-post-body p").each(function(){
    if ($(this).text().length > 500) {
      $(this).text($(this).text().substr(0, 495));
      $(this).append('...');
    }
  });
});
  </script>


    <div id="page-wrapper" class="">
    
    <section class="breadcrumb-wrapper" >
        <div class="container">
            <h2>New Blogs</h2>
            <ol class="breadcrumb">
                <li><a href="<%= root_path %>">Home</a></li>
                <li class="active">Rank Blogs</li>
            </ol>
        </div>
    </section>
<section class="content bg-color-2 right-sidebar" id="blog">
      <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-9 blog-content">
                <% @tags.each do |blog| %>
                <div class="blog-post">
                       <%= image_tag blog.avatar,:class => "img-responsive" ,:alt => ""%>
                        <div class="blog-post-detail">
                            <span><i class="fa fa-calendar"></i><%= blog.post_date.strftime("%d-%m-%Y") %></span>
                            <span><i class="fa fa-comment"></i>11</span>
                            <span><i class="fa fa-thumbs-up"></i>23</span>
                            <span class="text-light hidden-xs"><a href="#"><%= blog.category %></a>, <a href="#"><%= blog.tags %></a></span>
                        </div>
                        <div class="blog-post-body">
                        <a href=""><h3><%= link_to blog.name, blog %></h3></a>
                          <p><%= truncate(blog.details,:length => 500 ,escape: false).html_safe %></p>
                        <div>
                        <a href="<%= blog_path(blog) %>" class="btn btn-primary"><i class="fa fa-chevron-right"></i>Read More</a>
                        </div>
                        </div>
                </div>
                <% end %> 
                    <ul class="pagination">
                        <li ><%= will_paginate @tags, :container => false %></li>
                    </ul><br>
                </div>
                <br>
              <div class="col-md-4 col-lg-3 blog-sidebar">
              <div class="box">
                      <h3>Search</h3>
                        <form>
                            <fieldset>
                                <div class="form-group nospace">
                                <div class="input-group">
                                    <input type="text" class="form-control" id="search" placeholder="Search" required>
                                        <span class="input-group-btn"><button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button></span>
                                </div>
                                </div>
                            </fieldset>
                        </form>
                </div> 
                <%= render partial: "category_and_tags" %>
            </div>
      </div>
      </div>
</section>
</div>

app/views/blogs/edit.html.erb
<%= render 'form' %>
<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<%= javascript_include_tag "jquery-1.6.2.min", "jquery.tokeninput" %>
  <%= stylesheet_link_tag    "token-input", "token-input-facebook" %>
   <script type="text/javascript">
     $(document).ready(function() {
       $("#category").tokenInput('blogs/search_sphinx?q=', {
         theme: "facebook",
        hintText: "Search blog by Name",
         noResultsText: "No results found",
         searchingText: "Searching...",
         tokenLimit: 1
       });
     })
   </script>
  <script type="text/javascript">
  jQuery(document).ready(function($){
  $(".blog-post-body p").each(function(){
    if ($(this).text().length > 500) {
      $(this).text($(this).text().substr(0, 495));
      $(this).append('...');
    }
  });
});
  </script>
    <div id="page-wrapper" class="">
    
    <section class="breadcrumb-wrapper" >
        <div class="container">
            <h2>Anil Blogs</h2>
            <ol class="breadcrumb">
                <li><a href="<%= root_path %>">Home</a></li>
                <li class="active">My Blogs</li>
              <li><%= link_to 'New', new_blog_path(@blog), class: 'btn btn-primary' %> </li>
                
            </ol>
        </div>
    </section>
    <%= flash[:notice] %>
<section class="content bg-color-2 right-sidebar" id="blog">
<!-- <div class="col-md-3 col-md-offset-4 pull-right">
        <%#= form_tag search_blogs_path, :method => :get do %>
            <%#= text_field_tag :name %>
            <%#= submit_tag value='search'%>
        <%# end %>
    </div> -->
      <div class="container">
            <div class="row">
              
                <!-- BLOG CONTENT - START -->
                <div class="col-md-8 col-lg-9 blog-content">
                <% @blogs.each do |blog| %>
                <div class="blog-post">
                       <%= image_tag blog.avatar,:class => "img-responsive" ,:alt => ""%>
                        <div class="blog-post-detail">
                            <span><i class="fa fa-calendar"></i><%= blog.post_date.strftime("%d-%m-%Y") %></span>
                            <span class="text-light hidden-xs"><a href="#"><%= blog.category %></a>, <a href="#"><%= blog.tags %></a></span>
                        </div>
                        <div class="blog-post-body">
                        <a href=""><h3><%= link_to blog.name, blog %></h3></a>
                          <p><%= truncate(blog.details,:length => 500 ,escape: false).html_safe %></p>
                        <a href="<%= blog_path(blog) %>" class="btn btn-primary"><i class="fa fa-chevron-right"></i>Read More</a>
                        </div>
                </div>
                <% end %> 
                    <ul class="pagination">
                        <li ><%= will_paginate @blogs, :container => false %></li>
                    </ul><br>
                    <br>
                </div>
                <br>
              <div class="col-md-4 col-lg-3 blog-sidebar">
              <div class="box">
                      <h3>Search</h3>
                            <fieldset>
                              <div class="form-group nospace" >
                                <div class="input-group" style="width:100%;">
                                    <%= form_tag search_blogs_path, :method => :get do %>
                                      <%= text_field_tag('category', nil, class: 'input-group') %>
                                      <%#= submit_tag value="Search", class: 'btn btn-primary' %>
                                      <%= button_tag(type: "submit", class: "btn btn-primary") do %><i class="fa fa-search"></i>
                                      <% end %>
                                    <% end %>
                                </div>
                                </div>
                            </fieldset>
                </div>
                <%= render partial: "category_and_tags" %>
            </div>
      </div>
      </div>
</section>
</div>
 

app/views/blogs/latest_blogs.html.erb
<!DOCTYPE html>
<html>
<head>
    <!-- ==========================
      Meta Tags 
    =========================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- ==========================
      Title 
    =========================== -->
   <title>New Blog</title>
    
    <!-- ==========================
      Favicons 
    =========================== -->
  <link rel="shortcut icon" src="/assets/icons/favicon.ico">
  <link rel="apple-touch-icon" href="/assets/icons/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/assets/icons/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/assets/icons/apple-touch-icon-114x114.png">
    
    <!-- ==========================
      Fonts 
    =========================== -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet"/>
    
    <!-- ==========================
      CSS 
    =========================== -->
    
    <!-- ==========================
      JS 
    =========================== -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <style type="text/css">
body {background-image: linear-gradient(rgba(47, 195, 223, 0.6), rgba(47, 195, 223, 0.6)), url(../image/bg3.jpg);padding-top: 2%;}

  </style>
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=true"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="color-light-blue">
                <% @blogs.each do |blog| %>
                <div class="col-sm-6">
                	<div class="recent-blog-post">
                        <div class="post-date"><%= blog.post_date.strftime("%d-%m-%Y") %></div>
                        <h3 ><%= blog.name %></h3>
                        <p><%= truncate(blog.details,:length => 400 ,escape: false).html_safe %></p>
                        <a href="<%= blog_path(blog) %>">Read More<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <% end %>
                </body>
                </html>

app/views/blogs/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<script>
window.disqus_no_style = true;
$.getScript("http://disqus.com/forums/rapexegesis/embed.js")
</script>

<%= javascript_include_tag "jquery-1.6.2.min", "jquery.tokeninput" %>
  <%= stylesheet_link_tag    "token-input", "token-input-facebook" %>
   <script type="text/javascript">
     $(document).ready(function() {
       $("#category").tokenInput('blogs/search_sphinx?q=', {
         theme: "facebook",
        hintText: "Search blog by Name",
         noResultsText: "No results found",
         searchingText: "Searching...",
         tokenLimit: 1
       });
     })
   </script>
  <script type="text/javascript">
  jQuery(document).ready(function($){
  $(".blog-post-body p").each(function(){
    if ($(this).text().length > 500) {
      $(this).text($(this).text().substr(0, 495));
      $(this).append('...');
    }
  });
});
  </script> 


  <!-- ==========================
      FACEBOOK - SHARE BUTTON 
    =========================== -->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    
    
    <div id="page-wrapper" class="">
    <!-- ==========================
      HEADER - END 
    =========================== -->
    
    <!-- ==========================
      BREADCRUMB - START 
    =========================== -->
    <section class="breadcrumb-wrapper">
        <div class="container">
            <h2>My Blogs</h2>
            <ol class="breadcrumb">
                <li><a href="<%= root_path %>">Home</a></li>
                
            </ol>
        </div>
    </section>
  <!-- ==========================
      BREADCRUMB - END 
    =========================== -->

    <!-- ==========================
      BLOG - START 
    =========================== -->
    <%= flash[:notice] %>
     <section class="content bg-color-2 right-sidebar" id="blog">
      <div class="container">
            <div class="row">
              
                <!-- BLOG CONTENT - START -->
                <div class="col-md-8 col-lg-9 blog-content">
                  
                    <!-- BLOG POST -->
                    <div class="blog-post">
                      <!-- <div class="flex-video widescreen">
                          <iframe src="https://player.vimeo.com/video/23617801"></iframe>
                      </div> -->
                      <%= image_tag @blog.avatar,:class => "img-responsive" ,:alt => ""%>
                        <div class="blog-post-detail">
                            <span><i class="fa fa-calendar"></i><%= @blog.post_date.strftime("%d-%m-%Y") %></span>
                   <!--          <span><i class="fa fa-comment"></i>11</span>
                            <span><i class="fa fa-thumbs-up"></i>23</span> -->
                            <span class="text-light hidden-xs">
                            <% @cat = @blog.category.split(',') %>
                            <% @cat.each do |c| %>
                            <a href="#"><%= c %>&nbsp</a>
                            <% end %>
                            </span>
                            <span class="text-light hidden-xs">
                            <% @tag = @blog.tags.split(',') %>
                            <% @tag.each do |t| %>
                             <a href="#"><%= t %>&nbsp</a>
                            <% end %>
                            </span>
                        </div>
                        <div class="blog-post-body">
                        <h3><%= @blog.name %></h3>
                          <p><%= raw @blog.details %></p>
                          <p>Posted By: <%= @blog.author %>   

                        </div>

                    <% unless @blog.team.nil? %>
                    <div class="about-author" >
                        <div class="media">
                          <div class="pull-left">
                            <%= image_tag @blog.team.photo,:class => "img-responsive" ,:alt => "", :style=>"width:200px; height:200px" %><br>
                                <ul class="brands brands-sm brands-circle brands-inline text-center main">
                                  <li><a href="http://<%= @blog.team.facebook_link %>"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="http://<%= @blog.team.twitter_link %>"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="http://<%= @blog.team.googleplus_link %>"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>
                            <div class="media-body">
                              <h4 class="media-heading"><%= @blog.team.name %></h4>
                              <p><%= @blog.team.description %></p>
                              <ul class="list-unstyled list-inline" >
                                  <li style="font-size:12px;"><i class="fa fa-envelope"></i>&nbsp<%= @blog.team.email %></li>
                                    <li style="font-size:12px;"><a href="http://<%= @blog.team.linkedin_link %>"><i class="fa fa-linkedin-square"></i><%= @blog.team.linkedin_link %></a></li>
                                </ul>
                            </div>
                        </div><br>
                    </div>
                    <% end %>



                    <% if user_signed_in? and current_user.email == @blog.author %>
                    <br>
                    <div class="input-group">
                    <%= link_to 'Edit', edit_blog_path(@blog), class: 'btn btn-primary' %> 
                    <%= link_to 'Back', blogs_path , class: 'btn btn-primary'%>
                    </div>                    
                    <% end %>
                    


                <!-- BLOG CONTENT - END -->
              </div>
              </div>
                
                <!-- BLOG SIDEBAR - START -->
              <div class="col-md-4 col-lg-3 blog-sidebar">
              <div class="box">
                      <h3>Search</h3>
                        <form>
                            <fieldset>
                                <div class="form-group nospace">
                                    <div class="input-group">
                                    <%= form_tag search_blogs_path, :method => :get do %>
                                    <%#= text_field_tag :name %>
                                    <%#= submit_tag value='search'%>
                                       <input type="text" class="form-control" id="search" placeholder="Search" required>
                                        <span class="input-group-btn"><button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button></span>
                                        <% end %>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                </div>
                <%= render partial: "category_and_tags" %>
            </div>
      </div><br>
      <%- disqus_thread %>
       </div>
</section>
</div>
<style>
body.color-light-blue a{
  color:#15191A;
}
</style>
    <!-- ==========================
      BLOG - END 
    =========================== --> 
        
    <!-- ==========================
      FOOTER - START 
    =========================== -->
    <!-- ==========================
      FOOTER - END 
    =========================== -->
   
   
   
    <!-- ==========================
      JS 
    =========================== -->        
  

<!-- <p id="notice"><%#= notice %></p>

<p>
  <strong>Name:</strong>
  <%#= @blog.name %>
</p>

<p>
  <strong>Details:</strong>
  <%#= raw @blog.details %>
</p>

<p>
  <strong>Category:</strong>
  <%#= @blog.category %>
</p>

<p>
  <strong>Tags:</strong>
  <%#= @blog.tags %>
</p>

<p>
  <strong>Post date:</strong>
  <%#= @blog.post_date %>
</p>

<p>
  <strong>Blog video:</strong>
  <%#= @blog.blog_video %>
</p>

<p>
  <strong>Avatar:</strong>
  <%#= image_tag @blog.avatar %>
</p>

<p>
  <strong>User:</strong>
  <%#= @blog.user_id %>
</p>
<%#- disqus_thread %> -->
<%#= link_to 'Edit', edit_blog_path(@blog) %>
<%#= link_to 'Back', blogs_path %>